services:
  fish-no-fish:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app  # Mount the current directory
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/models/best.pt
      - MPLCONFIGDIR=/tmp/matplotlib
      - YOLO_CONFIG_DIR=/tmp/ultralytics
    restart: always
