name: Build and Push Image to Docker Hub

on:
  workflow_dispatch: # Allow manual triggering from GitHub Actions
  push:
    branches:
      - MOUSS_2016 # Automatically run on pushes to MOUSS_2016 branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    env:
      VERSION: 1.0.1 # Set this to your current version

    steps:
      # Step 1: Check out the repository to the runner
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Step 2: Set lower case owner name for consistent tags
      - name: Set lower case owner name
        run: echo "OWNER_LC=${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]' | awk -F "=" '{print "OWNER_LC="$2}' >> $GITHUB_ENV
        
      # Step 3: Log in to Docker Hub using GitHub repo secrets for authentication
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username stored in secrets
          password: ${{ secrets.DOCKER_TOKEN }} # Docker Hub token stored in secrets
      
      # Step 4: Build and push Docker image to Docker Hub
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./images/google-cloud-shell # Directory containing Dockerfile and context
          push: true # Push the built image to Docker Hub
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/gcs-fish-detector:latest # Latest tag
            ${{ secrets.DOCKER_USERNAME }}/gcs-fish-detector:${{ env.VERSION }} # Versioned tag

